import { NextResponse } from 'next/server';
import { Buffer } from 'buffer';

export async function POST(req) {
    try {
        const { imageUrl, title } = await req.json();
        const hfToken = process.env.HUGGINGFACE_API_TOKEN;

        console.log(`[AI-API] VERIFYING: ${imageUrl} | Title: ${title}`);

        if (!hfToken || hfToken.length < 10) {
            return NextResponse.json({ label: 'Civic Issue (Simulation)', score: 0.9, isVerified: true, isAI: false });
        }

        // 1. PRIMARY CIVIC CHECK (ResNet-50)
        const mainModel = "microsoft/resnet-50";
        const resnetResponse = await fetch(`https://router.huggingface.co/hf-inference/models/${mainModel}`, {
            headers: { "Authorization": `Bearer ${hfToken.trim()}`, "Content-Type": "application/json" },
            method: "POST",
            body: JSON.stringify({ inputs: imageUrl }),
        });

        const resnetResult = await resnetResponse.json();

        // 2. AI GENERATION CHECK (Fetch image first for Base64)
        const imgRes = await fetch(imageUrl);
        const imgBuffer = await imgRes.arrayBuffer();
        const base64Img = Buffer.from(imgBuffer).toString('base64');

        const detModel = "umm-maybe/AI-image-detector";
        const detResponse = await fetch(`https://router.huggingface.co/hf-inference/models/${detModel}`, {
            headers: { "Authorization": `Bearer ${hfToken.trim()}`, "Content-Type": "application/json" },
            method: "POST",
            body: JSON.stringify({ inputs: base64Img }),
        });
        const detResult = await detResponse.json();

        // --- ANALYSIS LOGIC ---

        // A. Is it AI Generated?
        let isAIGenerated = false;
        let aiScore = 0;

        if (Array.isArray(detResult)) {
            aiScore = detResult.find(r => r.label === 'artificial')?.score || 0;
            isAIGenerated = aiScore > 0.7;
        } else if (detResult?.error) {
            console.warn('[AI-API] AI Detector Error:', detResult.error);
            // Case where detector is down but ResNet is up - we proceed but log
        }

        // B. Is it a Civic Issue?
        const civicKeywords = [
            'pothole', 'road', 'street', 'asphalt', 'pavement', 'manhole', 'sewer', 'crack', 'drain',
            'trash', 'garbage', 'waste', 'recycling', 'bin', 'ashcan', 'junk', 'plastic', 'bag', 'debris',
            'light', 'lamp', 'electric', 'pole', 'sign', 'traffic', 'hazard', 'broken', 'damaged',
            'park', 'fountain', 'bench', 'sidewalk', 'curb', 'infrastructure', 'concrete'
        ];

        let topLabel = 'Unknown';
        let topScore = 0;
        let isCivicMatch = false;

        if (Array.isArray(resnetResult) && resnetResult.length > 0) {
            const top = resnetResult.slice(0, 5);
            topLabel = top[0].label;
            topScore = top[0].score;
            isCivicMatch = top.some(r => civicKeywords.some(key => r.label.toLowerCase().includes(key)));
        }

        // C. Is it relevant to the TITLE?
        const titleLower = (title || "").toLowerCase();
        const isRelevantToTitle = Array.isArray(resnetResult) && resnetResult.slice(0, 10).some(r => {
            const labelParts = r.label.toLowerCase().split(/[ ,]+/);
            return labelParts.some(p => p.length > 3 && titleLower.includes(p));
        });

        console.log(`[AI-API] Analysis: Civic=${isCivicMatch}, AI=${isAIGenerated}, TitleMatch=${isRelevantToTitle}`);

        // FINAL VERDICT
        if (isAIGenerated) {
            return NextResponse.json({
                isVerified: false,
                label: 'AI Generated Content Detected',
                score: aiScore,
                reason: 'Our safety system detected that this image was likely generated by AI. Please use a real photo.'
            });
        }

        if (!isCivicMatch && topScore < 0.3) {
            return NextResponse.json({
                isVerified: false,
                label: topLabel,
                score: topScore,
                reason: 'This image doesn\'t appear to be related to any city infrastructure or waste issues.'
            });
        }

        if (title && !isRelevantToTitle && topScore > 0.4) {
            // If AI is very confident it's something totally different than the title
            // (e.g. Title "Pothole" but AI sees "Cat")
            const titleKeywords = titleLower.split(' ').filter(w => w.length > 3);
            const hasKeywordMatch = titleKeywords.some(kw => topLabel.toLowerCase().includes(kw));

            if (!hasKeywordMatch) {
                return NextResponse.json({
                    isVerified: false,
                    label: topLabel,
                    score: topScore,
                    reason: `Image mismatch: The photo shows "${topLabel}", but your title is about "${title}". Please ensure the photo matches your report.`
                });
            }
        }

        return NextResponse.json({
            label: topLabel,
            score: topScore,
            isVerified: true,
            isAI: false
        });

    } catch (error) {
        console.error('AI ROUTE EXCEPTION:', error);
        return NextResponse.json({ error: "Connection error", isDown: true }, { status: 200 });
    }
}
