import { NextResponse } from 'next/server';
import { Buffer } from 'buffer';
const AI_CONFIDENCE_THRESHOLD = 0.65;

export async function POST(req) {
    try {
        const { imageUrl, title } = await req.json();
        const hfToken = process.env.HUGGINGFACE_API_TOKEN;

        console.log(`[AI-API] VERIFYING: ${imageUrl} | Title: ${title}`);

        if (!hfToken || hfToken.length < 10) {
            return NextResponse.json({ label: 'Civic Issue (Simulation)', score: 0.9, isVerified: true, isAI: false });
        }

        // 1. PRIMARY CIVIC CHECK (ResNet-50)
        const mainModel = "microsoft/resnet-50";
        const resnetResponse = await fetch(`https://router.huggingface.co/hf-inference/models/${mainModel}`, {
            headers: { "Authorization": `Bearer ${hfToken.trim()}`, "Content-Type": "application/json" },
            method: "POST",
            body: JSON.stringify({ inputs: imageUrl }),
        });

        const resnetResult = await resnetResponse.json();

        // 2. AI GENERATION CHECK (Fetch image first for Base64)
        const imgRes = await fetch(imageUrl);
        const imgBuffer = await imgRes.arrayBuffer();
        const base64Img = Buffer.from(imgBuffer).toString('base64');

        const detModel = "umm-maybe/AI-image-detector";
        const detResponse = await fetch(`https://router.huggingface.co/hf-inference/models/${detModel}`, {
            headers: { "Authorization": `Bearer ${hfToken.trim()}`, "Content-Type": "application/json" },
            method: "POST",
            body: JSON.stringify({ inputs: base64Img }),
        });
        const detResult = await detResponse.json();

        // --- ANALYSIS LOGIC ---

        // A. Is it AI Generated?
        let isAIGenerated = false;
        let aiScore = 0;

        if (Array.isArray(detResult)) {
            aiScore = detResult.find(r => r.label === 'artificial')?.score || 0;
            isAIGenerated = aiScore > 0.7;
        } else if (detResult?.error) {
            console.warn('[AI-API] AI Detector Error:', detResult.error);
            // Case where detector is down but ResNet is up - we proceed but log
        }

        // B. Is it a Civic Issue?
        const civicKeywords = [
            'pothole', 'road', 'street', 'asphalt', 'pavement', 'manhole', 'sewer', 'crack', 'drain',
            'trash', 'garbage', 'waste', 'recycling', 'bin', 'ashcan', 'junk', 'plastic', 'bag', 'debris',
            'light', 'lamp', 'electric', 'pole', 'sign', 'traffic', 'hazard', 'broken', 'damaged',
            'park', 'fountain', 'bench', 'sidewalk', 'curb', 'infrastructure', 'concrete'
        ];

        let topLabel = 'Unknown';
        let topScore = 0;
        let isCivicMatch = false;

        if (Array.isArray(resnetResult) && resnetResult.length > 0) {
            const top = resnetResult.slice(0, 5);
            topLabel = top[0].label;
            topScore = top[0].score;
            isCivicMatch = top.some(r => civicKeywords.some(key => r.label.toLowerCase().includes(key)));
        }

        // C. Is it relevant to the TITLE? (Enhanced Soft-Matching)
        const titleLower = (title || "").toLowerCase();

        // Synonyms to bridge human terms and AI labels
        const synonyms = {
            'pothole': ['pavement', 'road', 'asphalt', 'cobblestone', 'cracked'],
            'light': ['lamp', 'street', 'pole', 'electric', 'night'],
            'trash': ['garbage', 'waste', 'recycling', 'bin', 'plastic', 'bag', 'debris'],
            'sewer': ['drain', 'manhole', 'water', 'street', 'grating'],
            'tree': ['plant', 'branch', 'nature', 'wood'],
            'broken': ['damaged', 'crack', 'hazard']
        };

        const getExpandedKeywords = (term) => {
            let keys = [term];
            for (let root in synonyms) {
                if (term.includes(root)) keys.push(...synonyms[root]);
            }
            return keys;
        };

        const isRelevantToTitle = Array.isArray(resnetResult) && resnetResult.slice(0, 10).some(r => {
            const label = r.label.toLowerCase();
            const titleWords = titleLower.split(/[ ,._-]+/).filter(w => w.length > 2);

            // Check if any word in the title (or its synonyms) appears in the AI label
            return titleWords.some(word => {
                const expanded = getExpandedKeywords(word);
                return expanded.some(e => label.includes(e)) || label.includes(word);
            });
        });

        console.log(`[AI-API] Analysis: Civic=${isCivicMatch}, AI=${isAIGenerated}, TitleMatch=${isRelevantToTitle}`);

        // FINAL VERDICT
        if (isAIGenerated) {
            return NextResponse.json({
                isVerified: false,
                label: 'AI Generated Content Detected',
                score: aiScore,
                reason: 'Our safety system detected that this image was likely generated by AI. Please use a real photo.'
            });
        }

        // If it's a known civic issue but relevance failed, we check if the top label is just too different
        // Only reject on mismatch if confidence is very high
        const STRICT_MISMATCH_THRESHOLD = 0.7;

        if (title && !isRelevantToTitle && topScore > STRICT_MISMATCH_THRESHOLD) {
            const titleWords = titleLower.split(' ').filter(w => w.length > 3);
            const hasSoftMatch = titleWords.some(word => {
                const expanded = getExpandedKeywords(word);
                return expanded.some(e => topLabel.toLowerCase().includes(e));
            });

            if (!hasSoftMatch) {
                return NextResponse.json({
                    isVerified: false,
                    label: topLabel,
                    score: topScore,
                    reason: `Image mismatch: The photo appears to show "${topLabel}", which doesn't seem to match your title. Please verify both.`
                });
            }
        }

        // If it's not a civic match AND score is low, we reject
        if (!isCivicMatch && topScore < AI_CONFIDENCE_THRESHOLD) {
            return NextResponse.json({
                isVerified: false,
                label: topLabel,
                score: topScore,
                reason: 'This image doesn\'t appear to be related to any city infrastructure or waste issues.'
            });
        }

        return NextResponse.json({
            label: topLabel,
            score: topScore,
            isVerified: true,
            isAI: false
        });

    } catch (error) {
        console.error('AI ROUTE EXCEPTION:', error);
        return NextResponse.json({ error: "Connection error", isDown: true }, { status: 200 });
    }
}
